### PR TITLE
use custom httpbin replacement server

### PR DESCRIPTION
**Pull request by azdle**
I decided it was just easier to host it myself than to make people run it locally to be able to run the tests.

It's running https://github.com/azdle/litebin.

### CODE REVIEW

**Comment by azdle** [comment]
Whomp whomp, after all that it, it didn't fix it...

**Comment by FreeMasen** [comment]
It appears that the checks attached to this PR were all successful?

**Comment by azdle** [comment]
The latest run was, but it wasn't consistent: 
image

There's some variable latency, +/- multiple seconds, that I can't account for. I'd like to figure that out before I merge a solution.

**Comment by azdle** [comment]
Though, we could also just up the timeout I suppose. I've never seen it fail other than hitting the 5 second timeout.

**Comment by FreeMasen** [comment]
I was poking around yesterday and saw that httpbin is open source and the author has a docker container published that we _could_ run in CI if you don't want to keep hosting your project.

https://github.com/postmanlabs/httpbin

**Comment by azdle** [comment]
I've got litebin hosted on a proper server now.

Force-pushed out some leftover test commits, this should be good to go now.

**Review by FreeMasen — APPROVED** [review]

**Pull request merged**
