### PR TITLE
Fix waking thread with too many sockets

### PR DESCRIPTION
**Pull request by NoahCornell**
There is a small period of time where the waker for a cosock channel receiver is still active after the receiver has hit a timeout error. This happens after the `readythreads` are moved to the `wakethreads` and cosock starts iterating through the `wakethreads`. If a thread containing the sender runs before the thread containing the receiver, and sends data through the sender, then the waker for the receiver will be called and the thread will be re-added to `readythreads` even though cosock is already in the process of resuming that thread.

This can cause some confusing errors. If the receiver thread yields on a TCP socket operation, then the channel receiver will be returned in the `recvr` table. If the timing works out, it's possible that both the TCP socket and the receiver will be returned in the `recvr` table causing this [assert](https://github.com/cosock/cosock/blob/master/cosock/socket/internals.lua#L68) to fail.

This change closes the gap that this can happen by clearing the wakers held in `threadswaitingfor` before any threads are resumed.

### CODE REVIEW

**Review by FreeMasen — APPROVED** [review]

**Comment by azdle** [comment]
I'm not quite sure I follow the issue.

> This can cause some confusing errors. If the receiver thread yields on a TCP socket operation, then the channel receiver will be returned in the `recvr` table. If the timing works out, it's possible that both the TCP socket and the receiver will be returned in the `recvr` table causing this [assert](https://github.com/cosock/cosock/blob/master/cosock/socket/internals.lua#L68) to fail.

What is "the channel receiver" referring to here? I believe that if we are blocked within a socket operation (read: have yielded from a `passthroughbuilder` built function) then the thread should have no wakers other than the socket itself. If there's a channel waking a thread that's blocked in a socket op, I think that's a different bug.

Also, I'm concerned that this change could cause wakes to be lost if a thread is using `select`. Eg:

1. Thread yields via a select on a socket and a channel.
2. Socket becomes ready, thread gets added to `ready_threads`
3. cosock loops, hits this change and wakers are unset
4. Another thread sends on channel, but no waker is attached, nothing gets woken
5. Thread (from 1) wakes, is only informed about the socket readyness, doesn't know to check the channel
6. ???
7. deadlock?

**Comment by azdle** [comment]
>  If there's a channel waking a thread that's blocked in a socket op, I think that's a different bug.

Oh, this is a bug that can definitely happen as-is. And might actually be what you were describing? If it is, the thing I was missing is that it would have to happen on the next loop. That's how there can be something ready that we weren't waiting for.

`readythreads` gets a wake for something we've already queued up this loop, but if it yields somewhere  different it might have mismatched "readies" on the next loop.

---

Could we instead just check `readythreads` again just before starting each thread? I think that would solve both forms of this issue.

(I'm also now wondering if we need some sort of "is ready?" check for channels that select is aware of so that it would return them as ready without waiting for another wake if they were ready before being passed to select.)

**Review by azdle — APPROVED** [review]
I was waffling a bit on if I thought checking readythreads would be better anyway, but I think you probably had it right with this PR's way.

**Comment by NoahCornell** [comment]
> > If there's a channel waking a thread that's blocked in a socket op, I think that's a different bug.
> 
> Oh, this is a bug that can definitely happen as-is. And might actually be what you were describing? If it is, the thing I was missing is that it would have to happen on the next loop. That's how there can be something ready that we weren't waiting for.
> 
> `readythreads` gets a wake for something we've already queued up this loop, but if it yields somewhere different it might have mismatched "readies" on the next loop.

Sorry this was a confusing one and hard to explain, but yes that is what I was describing!

**Pull request merged**
